export const PC_EN_DICT: Record<string, string> = {
  // Product name
  '墨刀AI': 'Prodes AI',
  '墨刀 AI': 'Prodes AI',
  '墨刀AI设计助手': 'Prodes AI design assistant',
  '展开左侧栏': 'Expand sidebar',
  '新建项目': 'New project',
  '购买': 'Buy',
  '生成一个电商购物App首页': 'Generate an e-commerce shopping app home screen',
  '你好！我是墨刀 AI 设计助手，专注于完整的端到端产品架构生成与开发。': "Hi! I'm Prodes AI design assistant, focused on end-to-end product design and build.",
  '你可以对我说："生成一个带深色模式的现代任务管理 SaaS 后台" 或 "帮我做一个电商小程序的商品列表页"。': 'Try: "Build a modern task SaaS admin with dark mode" or "Design a product list page for an e-commerce mini app".',
  '分享完整项目': 'Share entire project',
  '分享当前预览': 'Share current preview',
  '包含整个对话记录和所有生成的内容': 'Share the whole conversation and everything generated in it',
  '仅分享当前正在预览的内容': 'Only share the content currently being previewed',
  '展开助手': 'Expand assistant',
  '墨刀AI的虚拟电脑': 'Prodes AI virtual computer',
  '已完成编辑': 'Edited',
  '设计评审': 'Design review',
  '设计评审文档': 'Design review doc',
  '分享': 'Share',
  '复制': 'Copy',
  '下载': 'Download',
  '历史版本': 'History',
  '设置类别': 'Settings',
  '设置': 'Settings',
  '目录': 'Files',
  '收起目录': 'Collapse files',
  '请先输入需求后再发送': 'Please enter a prompt before sending.',
  '发送': 'Send',
  '请框选要调整的区域并告诉AI如何修改': 'Select an area and tell the AI what to change',
  '添加到对话': 'Add to chat',
  '暂无可预览的内容': 'Nothing to preview',
  '确定要撤回该项目的发布吗？': 'Withdraw this publish?',
  '撤回后线上链接将立即失效。': 'The live link will be disabled immediately.',
  '撤回成功': 'Withdrawn',
  '确定': 'Confirm',
  '截图优化': 'Screenshot mode',
  'PC 端': 'PC',
  'Pad 端': 'Pad',
  '已保存至云端': 'Saved to cloud',
  '撤销上一步': 'Undo',
  '重做': 'Redo',
  '下载当前文件': 'Download current file',
  '下载所有文件': 'Download all files',
  '链接访问权限': 'Link access',
  '仅限自己': 'Only me',
  '仅自己可见': 'Visible only to you',
  '公开': 'Public',
  '获得链接的人可访问': 'Anyone with the link can access',
  '回放模式': 'Replay mode',
  '复制链接': 'Copy link',
  '发布网站': 'Publish site',
  '项目名称': 'Project name',
  '当前状态': 'Status',
  '已发布': 'Published',
  '未发布': 'Not published',
  '最近发布时间': 'Last published',
  '访问链接': 'Access link',
  '点击在新标签页打开': 'Open in new tab',
  '点击在新标签页打开预览': 'Open preview in new tab',
  '发布后可访问': 'Available after publishing',
  '产品已下架': 'This product is no longer available',
  '该产品已下架或链接无效，无法继续访问。':
    'This product has been taken down or the link is invalid.',
  '已发布站点': 'Published site',
  '已下架': 'Delisted',
  '生成同款': 'Recreate this style',
  '帮助': 'Help',
  '本页面为已发布作品的预览。点击「生成同款」前往墨刀 AI；点「?」可再次查看此说明。':
    'Preview of a published page. “Recreate this style” opens Modao AI; “?” shows this note again.',
  '保存': 'Save',
  '取消': 'Cancel',
  '删除': 'Delete',
  '删除项目': 'Delete project',
  '确定要删除项目吗？删除后，已发布的应用和分享链接将一并失效':
    'Are you sure you want to delete this project? Published apps and sharing links will stop working.',
  '此操作不可恢复。': 'This action cannot be undone.',
  '编辑域名前缀': 'Edit subdomain',
  '撤回': 'Withdraw',
  '正在撤回...': 'Withdrawing...',
  '✅ 更新成功！': 'Update successful',
  '更新': 'Update',
  '正在更新...': 'Updating...',
  '更新成功': 'Updated',
  '✅ 发布成功！网站已上线': 'Published. Your site is live.',
  '发布': 'Publish',
  '正在发布...': 'Publishing...',
  '刚刚': 'Just now',
  '{{n}} 分钟前': '{{n}} min ago',
  '{{n}} 小时前': '{{n}} hr ago',
  '{{n}} 天前': '{{n}} d ago',
  '等待生成内容': 'Waiting for output',
  '在左侧输入需求，AI将为您生成产品并在右侧展示': 'Describe your needs on the left. The AI will generate and show results on the right.',
  'AI 正在生成中，请稍候...': 'Generating. Please wait...',
  'AI 正在绘制界面结构并添加样式...': 'Building layout and styles...',
  '代码正在流式渲染...': 'Streaming code...',
  '接收流式代码中...': 'Receiving stream...',
  '等待代码生成...': 'Waiting for code...',
  '暂不支持当前模式': 'Not supported yet',
  '此 Tab 规划中，将在后续版本上线': 'Planned for a future release',
  '分析需求结构...': 'Analyzing requirements...',
  '搭建页面框架': 'Building page structure',
  '已完成创建 {{file}}': 'Created {{file}}',
  '正在整合样式资源...': 'Integrating styles...',
  '正在执行...': 'Running...',
  '正在生成代码（{{n}} 字符）...': 'Generating code ({{n}} chars)...',
  '已为您生成以下内容，点击卡片可在右侧查看：': 'Generated the following. Click a card to view on the right:',
  '文档': 'Doc',
  '单页': 'Single page',
  '多页': 'Multi-page',
  '应用': 'App',
  'App原型': ' app prototype',
  '该链接已被占用': 'This link is taken',
  '正在理解需求...': 'Understanding requirements...',
  '分析产品架构...': 'Analyzing product structure...',
  '准备生成方案...': 'Preparing a solution...',
  '请根据提供的截图优化': 'Optimize based on the provided screenshot',
  '电商购物App原型': 'E-commerce shopping app prototype',
  '墨刀 AI 设计助手': 'Prodes AI design assistant',
  '导出至墨刀': 'Export to Prodes',
  '导出至墨刀原型': 'Export to Prodes prototype',
  '导出至墨刀设计': 'Export to Prodes design',
  '已导出至墨刀原型': 'Exported to Prodes prototype',
  '已导出至墨刀设计': 'Exported to Prodes design',
  'HTML 转墨刀原型': 'HTML to Prodes prototype',
  '产品团队': 'Product team',
  '超级智能体': 'AI assistant',
  '下午好，我能如何帮助您': 'Good afternoon. How can I help',
  '热门生成': 'Popular generations',
  '技能': 'Skills',
  '搜索技能': 'Search skills',
  '技能管理': 'Skill management',
  '技能管理说明': 'Import, enable, disable, or reorder skills here. Full management is coming soon.',
  '管理已安装技能，设置自动或手动触发，并支持从本地导入或通过对话新建。': 'Manage installed skills, switch between auto and manual trigger, and add skills from local folders or by chat.',
  '知道了': 'Got it',
  '完成': 'Done',
  '暂无匹配技能': 'No matching skills',
  '试试切换筛选项，或从本地导入技能目录。': 'Try another filter, or import a local skill folder.',
  '从本地导入': 'Import locally',
  '通过对话新建': 'Create by chat',
  '新建技能': 'New skill',
  '筛选技能': 'Filter skills',
  '全部技能': 'All skills',
  '内置技能': 'Built-in',
  '用户添加': 'User added',
  '自动触发': 'Auto trigger',
  '手动触发': 'Manual trigger',
  '已设置为自动触发': 'Set to auto trigger',
  '已设置为手动触发': 'Set to manual trigger',
  '命中场景时自动调用': 'Runs automatically when the scenario matches',
  '仅在手动选择时调用': 'Runs only when selected manually',
  '草稿': 'Draft',
  '用户添加技能': 'User-added skill',
  '新技能草稿': 'New skill draft',
  '通过对话新建，等待补充技能说明': 'Created via chat, waiting for details',
  '本地导入 · {{n}} 个文件': 'Imported locally · {{n}} files',
  '新闻摘要': 'News summary',
  '阅读链接并输出要点摘要': 'Summarize links into key takeaways',
  'PPT 演示文稿': 'PowerPoint deck',
  '生成、编辑与阅读演示文稿': 'Create, edit, and read presentation files',
  'PDF 文档生成': 'PDF generation',
  '从需求生成结构化 PDF': 'Generate structured PDFs from requirements',
  'Word 文档生成': 'Word document drafting',
  '长文档大纲与段落起草': 'Outlines and paragraph drafting for long docs',
  'Excel 文件处理': 'Excel workflows',
  '表格清洗、透视与公式建议': 'Cleaning, pivots, and formula suggestions',
  'Android 原生开发': 'Android native',
  'Kotlin 界面与 Gradle 工程辅助': 'Kotlin UI and Gradle project assistance',
  '浏览器自动化': 'Browser automation',
  'CDP 驱动的页面操作与数据采集': 'CDP-driven page actions and data capture',
  '文件整理': 'File organization',
  '目录归类、命名规则与批量重命名': 'Folders, naming rules, and batch renames',
  '返回墨刀工作台': 'Back to Modao workspace',
  '空间列表': 'Spaces',
  '免费': 'Free',
  '已过期': 'Expired',
  '企业VIP': 'Enterprise VIP',
  '成员数': 'Members',
  '个人空间': 'Personal space',

  // Extra specific strings inside sub-cards
  '图片转原型': 'Image to Prototype',
  '你想生成什么': 'What do you want to generate',
  '想生成什么应用': 'What app do you want to build',
  '想设计什么原型': 'What prototype do you want to design',
  '想策划什么': 'What do you want to plan',
  '想生成什么图片': 'What images to generate',
  '想生成什么视频': 'What videos to generate',
  '想生成什么PPT': 'What slides to generate',
  '想生成什么流程/导图': 'What flowcharts & mind maps to generate',
  '想生成什么研发测试': 'What QA & technical outputs to generate',
  '想生成什么运营推广': 'What marketing assets to generate',
  '想生成什么UI设计': 'What UI design to work on',
  '想从参考生成什么': 'What to build from references',
  '想搭建什么数据能力': 'What data capability to build',
  '想配置什么SaaS能力': 'What SaaS capability to configure',
  '参考转应用': 'Build from references',
  '接口与数据服务': 'APIs & data services',
  'SaaS化交付': 'SaaS delivery toolkit',
  '精选参考转应用': 'Featured reference builds',
  '精选接口与数据服务': 'Featured APIs & data services',
  '精选SaaS化交付': 'Featured SaaS delivery',
  '上传截图、粘贴 Figma/网页链接或描述对标目标，我将输出可部署的全栈应用方案与拆分步骤。':
    'Upload screenshots, paste Figma/web links, or describe a benchmark—get a deployable full-stack plan with clear build steps.',
  '描述领域模型、数据源或联调痛点，我将生成 API/ETL/Mock/Webhook 等工程化方案与接口约定。':
    'Describe domain models, data sources, or integration pain points—get API/ETL/Mock/Webhook designs with interface contracts.',
  '描述租户模型、计费维度或合规要求，我将输出多租户、订阅计费、配额与审计等 SaaS 交付设计。':
    'Describe tenant models, billing dimensions, or compliance needs—get multi-tenant, billing, quota, and audit delivery designs.',
  '可直接输入一句话描述需求，也可先选下方能力标签再点探索想法。':
    'Describe your need in one line, or pick a capability below and explore ideas.',
  '探索想法': 'Ideas to explore',
  '换一批': 'Shuffle',
  'B端管理系统': 'B-end admin system',
  '移动端应用': 'Mobile client app',
  '可视化大屏应用': 'Visual large-screen app',
  '官网与落地页': 'Website & landing page',
  '轻量工具应用': 'Lightweight tool app',
  '多租户与SaaS交付': 'Multi-tenant & SaaS delivery',
  '截图转全栈应用': 'Screenshot to full-stack app',
  'Figma转应用工程': 'Figma to app codebase',
  '网页参考转应用': 'Web reference to app',
  'HTML包部署应用': 'HTML bundle to deployable app',
  'REST API与中台': 'REST APIs & platform layer',
  '数据同步与ETL控制台': 'Data sync & ETL console',
  'Mock与联调沙箱': 'Mock & integration sandbox',
  'Webhook与事件总线': 'Webhooks & event bus',
  '多租户与工作区': 'Multi-tenant workspaces',
  '订阅与计费后台': 'Subscription & billing admin',
  '配额用量中心': 'Quota & usage center',
  '审计与权限策略': 'Audit & access policies',
  '导入Figma文件': 'Import Figma File',
  '导入参考链接': 'Import Reference Link',
  '粘贴参考页面、Figma 分享页或其他在线内容链接': 'Paste a reference page, Figma share page, or other online content link',
  '请输入 Figma / 墨刀 / 网页链接': 'Enter a Figma, MockingBot, or web link',
  '导入': 'Import',
  '上传图片，一键转为原型': 'Upload image, convert to prototype',
  '需求文档PRD': 'PRD Document',
  'PRD文档': 'PRD Document',
  'PRD需求文档': 'PRD & Requirements Document',
  '可视化大屏': 'Visual Dashboard',
  '经营看板 / 驾驶舱 / 趋势大屏': 'Business dashboards, cockpits, and trend screens',
  'App/小程序': 'App / Mini Program',
  '电商 / 问诊 / 社交移动原型': 'Mobile prototypes for commerce, telehealth, and social apps',
  'B端管理后台': 'B-end Admin Console',
  'CRM / ERP / 权限配置后台': 'CRM, ERP, and permission-based admin consoles',
  '参考图复刻原型': 'Reference-based Prototype Recreation',
  '需求结构 / 用户故事 / 验收标准': 'Requirement structure, user stories, and acceptance criteria',
  'AI生成视频': 'AI Video',
  'AI生成PPT': 'AI PPT',
  '生成HTML格式': 'HTML slides',
  '生成图片格式': 'Image slides',
  '生成PPTX格式': 'PPTX export',
  '美化PPT': 'Polish deck',
  '网页/HTML 幻灯片，可嵌入、全屏播': 'Web/HTML slides for embed & fullscreen',
  '逐页出图、长图分镜、便于分享': 'Per-page images & storyboard strips for sharing',
  '标准 PPTX 文件，可在 Office 续编': 'Standard PPTX for editing in Office',
  '上传现稿，优化排版、配色与层级': 'Upload deck; refine layout, colors & hierarchy',
  '请描述主题或上传资料，我将输出可演示的 HTML 幻灯片与页面结构...':
    'Describe the topic or upload material—I will output presentable HTML slides and page structure...',
  '请描述分镜或上传参考，我将生成各页 16:9 配图或长图版式...':
    'Describe the storyboard or upload references—I will generate 16:9 per-page images or a long-strip layout...',
  '请描述演讲目标或上传大纲，我将生成可下载的 PPTX 结构与初稿...':
    'Describe the talk goal or upload an outline—I will generate a downloadable PPTX structure and first draft...',
  '请上传现有PPT，我将统一版式、配色与信息层级并给出改稿建议...':
    'Upload your deck—I will align layout, color, and information hierarchy and suggest edits...',
  '快速生成包含详细逻辑的产品需求文档': 'Generate PRD with logic details',
  '需求结构与验收要点': 'Requirement structure and acceptance criteria',
  '需求结构 / 用户故事 / 验收项': 'Requirement structure, user stories, and acceptance criteria',
  'HTML转原型': 'HTML to Prototype',
  '上传HTML文件，一键转为原型': 'Upload HTML, convert to prototype',
  '生成图片': 'Generate Image',
  '输入描述或参考图，生成图片': 'Input prompt or image, generate picture',
  '生成原型概念图': 'Generate Concept Map',
  '激发脑暴，快速产出概念原型': 'Brainstorm and output concept map',
  '功能交互文档': 'Functional Interaction Doc',
  'AI 生成产品功能与交互说明文档': 'Generate product feature and interaction documentation',
  'AI 生产品功能与交互文档': 'Generate feature & interaction doc',
  'UI规范评审': 'UI Spec Review',
  '检查设计一致性与规范': 'Check design consistency & rules',
  '竞品分析': 'Competitive Analysis',
  '多维度对比分析，自动输出调研报告': 'Analyze competitors and output report',
  '用户调研': 'User Research',
  '自动生成调研问卷和用户画像分析': 'Generate survey and user persona',
  '产品方案评审': 'Product Solution Review',
  '智能评审原型方案，提供优化建议': 'Review prototype and suggest',
  '产品规划': 'Product Planning',
  '制定版本迭代计划，生成Roadmap': 'Create iteration plan & roadmap',
  'AI PPT': 'AI PPT',
  'PPT大纲初稿': 'PPT Outline Draft',
  '一键提取核心结构并生成报告大纲': 'Extract structure and outline report',
  '汇报大纲与版式初稿': 'Presentation outline and first-pass layout',
  '路演 / 汇报 / 培训演示稿': 'Pitch, report, and training deck drafts',
  'AI美化PPT': 'AI PPT Beautifier',
  '一键优化排版配色，提升文档质感': 'Optimize layout and colors',
  '流程图': 'Flowchart',
  '描述业务逻辑，自动绘制标准流程图': 'Draw standard flowchart from logic',
  '思维导图': 'Mind Map',
  '梳理核心思路，一键转为思维导图': 'Organize core ideas into mind map',
  '用户旅程图': 'User Journey Map',
  '可视化用户行为路径与情感体验': 'Visualize user path & experience',
  '测试用例生成': 'Test Case Generation',
  '自动解析需求，生成完整测试用例': 'Parse requirements, output test cases',
  '技术方案生成': 'Tech Solution Generation',
  '根据需求生成系统架构与技术选型': 'Generate arch & tech stack',
  '技术方案评估': 'Tech Solution Evaluation',
  '分析技术方案可行性，识别潜在风险': 'Analyze feasibility & identify risks',
  '生成视频': 'Generate Video',
  '最具突破性的 AI 能力': 'Groundbreaking AI capability',
  '生成营销图': 'Generate Marketing Image',
  '产品卖点一键生成推广配图': 'Generate promotional visuals from product highlights',
  '快速生成推广配图': 'Quickly generate promotional images',
  'SEO文章生成': 'SEO Article Generation',
  '生成利于搜索引擎收录的推广文章': 'Generate SEO-friendly articles',

  // New: recommend / image & video cards
  '移动端App与小程序': 'Mobile App & Mini Program',
  '电商 / 生鲜 / 问诊 等多页 C 端原型一次出': 'E‑commerce, grocery, telehealth — multi‑page consumer prototype',
  'AI生成图片': 'AI Image',
  'AI生图': 'AI Image',
  '视觉物料生图': 'Visual Asset Generation',
  '主视觉 / Banner / 插画，一句话出图': 'Key visuals, banners, illustrations in one sentence',
  '主视觉 / Banner / Logo': 'Key visual, banner, or logo',
  '海报 / KV / Banner / Logo': 'Posters, key visuals, banners, and logos',
  '文生视频 / 图生视频 / 数字人口播': 'Text‑to‑video, image‑to‑video, AI presenter',
  '图片转视频': 'Image to Video',
  '静态图片一键生成动态镜头视频': 'Turn still images into motion-shot video',
  '数字人口播': 'AI Talking Avatar',
  '脚本文案转为口播视频内容': 'Turn scripts into talking-avatar video',
  '宣传短片': 'Promo Video',
  '生成产品 / 活动宣传短片脚本与画面': 'Generate promo video scripts and scenes for products or campaigns',
  'Logo设计': 'Logo Design',
  '多风格品牌 Logo 概念一次出': 'Multiple brand logo concepts at once',
  '海报设计': 'Poster Design',
  '活动 / 节日 / 新品发布海报': 'Campaigns, festivals, launch posters',
  '主视觉KV': 'Key Visual',
  '品牌 / 发布会 / 活动主视觉': 'Brand, launch, event key visuals',
  '逻辑图表': 'Logic Diagram',
  '信息层级、关系和推演逻辑可视化': 'Visualize hierarchies, relationships and reasoning',
  '组织架构图': 'Org Chart',
  '团队 / 部门 / 汇报关系可视化': 'Visualize teams, departments & reporting',
  '架构图': 'Architecture Diagram',
  '系统模块和业务结构一图梳理': 'Map system modules and business structure in one diagram',
  '关系图': 'Relationship Diagram',
  '人物、要素和节点关系清晰呈现': 'Clearly show relationships between people, elements and nodes',
  '矩阵图': 'Matrix Diagram',
  '二维维度比较与分层表达': 'Present comparisons across two dimensions',
  '对比图': 'Comparison Chart',
  '对象差异、优劣势和变化对照': 'Compare differences, tradeoffs and changes across items',

  // New: recommend card descriptions tightened
  '监控 / 运营 / 能耗看板，多文件 HTML 可演示交付':
    'Monitoring, ops, energy dashboards — multi‑file HTML, demo‑ready',
  'CRM / 权限 / 表格 / 工单 等 B 端后台原型':
    'CRM, permissions, tables, tickets — common B‑end admin prototypes',
  '参考图 / 截图高保真还原与风格迁移':
    'Faithful replication from reference images or style migration',
  '高保真还原参考图 / 对标 App 迁移':
    'High‑fidelity replication or cross‑app style migration',

  // Intent mismatch extras
  '当前挂在「AI生成视频」，但描述像页面/原型。若要做界面，可点标签 × 去掉后改选「AI生成原型」。':
    'You picked "AI Video" but the prompt reads like a UI/prototype. Remove the tag with ×, then switch to "AI Prototype".',

  '一句话生成主视觉 / Banner / 插画':
    'One‑sentence key visuals, banners, and illustrations',
  '请描述你要生成的图片内容或上传参考图，例如：科技感产品主视觉、电商 Banner、扁平插画...':
    'Describe the image or upload a reference, e.g. a tech‑style key visual, e‑commerce banner, flat illustration...',
  '请描述视频主题、风格与镜头，例如：15 秒产品开箱短视频、赛博朋克风城市延时、AI 数字人口播...':
    'Describe topic, style, and shots, e.g. 15s product unboxing, cyberpunk city timelapse, AI presenter...',
  '请上传图片并描述镜头运动、时长与风格，我将生成对应的视频片段...':
    'Upload an image and describe camera motion, duration and style, and I will generate the video clip...',
  '请提供文案和角色风格，我将生成口播视频脚本与画面...':
    'Provide script and avatar style, and I will generate the talking-avatar video...',
  '请描述产品、品牌或活动主题，我将生成宣传短片方案...':
    'Describe the product, brand, or campaign and I will generate a promo video concept...',
  '请描述品牌名、行业与气质关键词，我将生成多款 Logo 概念...':
    'Describe the brand name, industry, and tone, and I will generate multiple logo concepts...',
  '请描述活动主题、风格与关键信息，我将生成可直接使用的海报...':
    'Describe the event theme, style, and key info, and I will generate ready‑to‑use posters...',
  '请描述品牌/活动主题与核心视觉元素，我将生成主视觉 KV 方案...':
    'Describe the brand/event theme and key visual elements, and I will generate key visuals...',
  '请描述要梳理的逻辑结构或信息层级，我将生成清晰的逻辑图表...':
    'Describe the logic structure or information hierarchy and I will generate a clear logic diagram...',
  '请描述团队/部门结构或上传名单，我将生成清晰的组织架构图...':
    'Describe the team/department structure or upload a roster, and I will generate a clean org chart...',
  '请描述系统模块或业务结构，我将生成对应的架构图...':
    'Describe the system modules or business structure and I will generate an architecture diagram...',
  '请描述对象之间的关系与连接方式，我将生成关系图...':
    'Describe the relationships and connections between objects and I will generate a relationship diagram...',
  '请描述要对比的维度和对象，我将生成矩阵图...':
    'Describe the dimensions and items to compare and I will generate a matrix diagram...',
  '请描述需要比较的对象和指标，我将生成清晰的对比图...':
    'Describe the items and metrics to compare and I will generate a clear comparison chart...',
  '请描述业务类型与核心页面，例如：生鲜电商小程序首页 + 分类 + 商详 + 购物车；或在线问诊 App 的挂号 + 问诊 + 处方流程...':
    'Describe the business type and core pages, e.g. grocery mini app home + categories + detail + cart, or telehealth app registration + consultation + prescription...',
  '请上传设计稿或界面截图，我将检查设计一致性与规范...':
    'Upload designs or screenshots and I will review consistency and spec compliance...',
  '请输入产品阶段目标，我将制定版本迭代计划和 Roadmap（以路线图/里程碑为主，不默认输出高保真页面）...':
    'Describe the product phase goals and I will build an iteration plan and roadmap (milestones first, not high‑fidelity screens)...',
  '一张主视觉': 'A key visual',
  '点击取消该分类筛选': 'Click to clear this category filter',
  '帮我生成一张科技感十足的产品主视觉，突出 AI 与速度，蓝紫色渐变，现代扁平插画风格。':
    'Generate a tech-forward product key visual highlighting AI and speed, blue-purple gradient, modern flat illustration style.',

  // Common UI
  '首页': 'Home',
  '知识库': 'Library',
  '历史对话': 'History',
  '新建对话': 'New chat',
  '收起左侧栏': 'Collapse sidebar',
  '下载移动端': 'Get mobile app',
  '扫码下载移动端，把专业墨刀AI能力装进口袋': 'Scan to get the mobile app',
  '联系客服': 'Contact support',
  '精选案例': 'Featured',
  '精选生成应用': 'Featured app generation',
  '精选原型设计': 'Featured prototype design',
  '精选原型': 'Featured prototypes',
  '精选应用': 'Featured apps',
  '精选需求策划': 'Featured requirement planning',
  '精选图片': 'Featured images',
  '精选视频': 'Featured videos',
  '精选PPT': 'Featured decks',
  '精选流程/导图': 'Featured flow & mind maps',
  '精选研发测试': 'Featured QA & testing',
  '精选运营推广': 'Featured marketing',
  '精选UI设计': 'Featured UI design',
  '全部': 'All',
  '筛选案例子类': 'Filter case category',
  '试试这样描述': 'Try one of these prompts',
  '点击填入输入框': 'Click to fill the input',
  '该能力相关案例整理中': 'Examples for this capability are being prepared',
  '网页端': 'Web',
  '移动端': 'Mobile',
  'SaaS业务控制台': 'SaaS dashboard',
  'SaaS落地页设计': 'SaaS landing page',
  '文旅一站式平台': 'Travel platform',
  '古风数字景区App设计': 'Scenic app',
  '生鲜商城购物车': 'Grocery cart',
  '生鲜/电商APP原型': 'E-commerce app',
  '在线视频教学平台': 'Online learning',
  '在线教育界面设计': 'Education UI',
  '运营与监控数据大屏': 'Ops & metrics dashboard',
  '多指标分区与实时告警': 'KPI zones & live alerts',
  '数据可视化运营大屏案例': 'Data dashboard showcase',
  'B 端权限与列表后台': 'RBAC & data tables',
  'CRM / 工单 / 角色权限': 'CRM, tickets, roles',
  '企业后台管理系统案例': 'Enterprise admin showcase',
  '参考界面高保真复刻': 'Pixel-faithful from reference',
  '截图或对标 App 迁移': 'From screenshot or app style',
  '界面复刻设计案例': 'UI replication showcase',
  '结构化需求与流程': 'Structured reqs & flows',
  '在线问诊 PRD 示例': 'Telehealth PRD sample',
  '需求文档 PRD 案例': 'PRD document showcase',
  '新建': 'Create',
  '更多': 'More',
  '请输入任何产品领域的需求或问题...': 'Describe what you want to build...',
  '可直接输入一句话：大屏看板、企业后台、小程序/电商、PRD、或界面复刻；也可先选下方能力标签。':
    'Describe in one line: dashboard, admin console, mini app/e‑commerce, PRD, or UI replication—or pick a capability tag below.',
  '快速试用': 'Try a sample',
  '运营大屏': 'Ops dashboard',
  '设计一个智慧医院运营数据大屏，包含顶部 KPI、中间趋势图、底部病区告警列表，深色主题，多文件 HTML 交付。':
    'Design a smart hospital operations dashboard: top KPIs, trend charts, ward alerts at the bottom, dark theme, multi-file HTML.',
  '企业后台': 'Admin console',
  '生成一个企业后台管理系统：左侧菜单、顶部面包屑、用户列表带筛选与分页、角色权限说明，多页面 HTML。':
    'Build an enterprise admin: sidebar, breadcrumbs, user list with filters and pagination, role permissions, multi-page HTML.',
  '小程序首页': 'Mini app home',
  '做一个生鲜电商小程序首页：轮播、分类入口、推荐商品瀑布流、底部 Tab，移动端风格。':
    'A fresh grocery mini app home: carousel, categories, product feed, bottom tabs, mobile style.',
  'PRD': 'PRD',
  '为在线问诊 App 撰写 PRD：用户角色、核心流程、异常流程、消息推送与合规要点，Markdown 输出。':
    'Write a PRD for a telehealth app: roles, core flows, edge cases, push notifications, compliance, Markdown output.',
  '当前挂在「生图」类能力，描述更像页面/原型。若要做界面，可点标签 × 去掉后选择「AI生成原型」或「图片转原型」。':
    'You picked an image mode but the prompt sounds like UI/prototype. Remove the tag with ×, then choose “AI Prototype” or “Image to Prototype”.',
  '「产品规划」默认输出路线图/里程碑。若主要想直接出高保真页面，建议选择「AI生成原型」。':
    '“Product Planning” outputs roadmaps. For high-fidelity screens, prefer “AI Prototype”.',
  '极速': 'Fast',
  '深度': 'Deep',
  '快速生成': 'Quick draft',
  '深度思考': 'Deeper reasoning',
  '主题色': 'Theme',
  '设计系统': 'Design system',
  '外观': 'Appearance',
  '亮色': 'Light',
  '暗色': 'Dark',
  '自动': 'Auto',
  '蓝': 'Blue',
  '绿': 'Green',
  '紫': 'Purple',
  '橙': 'Orange',
  '黄': 'Yellow',
  '红': 'Red',
  '极速模式': 'Fast',
  '深度模式': 'Deep',
  '响应速度更快，适合简单问答': 'Faster, best for simple tasks',
  '内容质量更高，适合复杂任务': 'Better quality for complex tasks',
  '工作台': 'Workspace',

  // Tabs
  '预览': 'Preview',
  '编辑': 'Edit',
  '代码': 'Code',
  '配置': 'Settings',
  '分析': 'Analytics',

  // Tab Labels
  '推荐': 'Recommend',
  '生成应用': 'Generate App',
  '原型设计': 'Prototyping',
  '产品策划': 'Planning',
  '需求策划': 'Requirement planning',
  '图片': 'Images',
  '视频': 'Video',
  'PPT': 'PPT',
  '图表与图片': 'Charts',
  '图表流程图': 'Charts & Flow',
  '图示图表': 'Diagrams & Charts',
  '流程与图表': 'Flowcharts & Diagrams',
  '流程/导图': 'Flow / Mind Maps',
  '研发测试': 'Dev & Test',
  '运营推广': 'Marketing',
  'UI设计': 'UI Design',
  '营销与多媒体': 'Marketing',
  '图片视频': 'Image & Video',

  // Generation Cards & Descriptions
  'AI生成应用': 'AI Generate App',
  'React / Vue 全栈工程，含后端服务，支持发布上线':
    'React / Vue full‑stack project with backend services, ready to publish online',
  '请描述你的应用需求，我将生成 React / Vue 全栈代码工程（含页面、状态、后端服务与接口），并支持发布到线上运行...':
    'Describe your app and I will generate a React / Vue full‑stack codebase (pages, state, backend services & APIs), publishable to production...',
  'AI生成Web应用': 'AI Generate Web App',
  'React / Vue 站点 + 后端与接口，可部署为线上环境':
    'React / Vue site plus backend & APIs, deployable as a live environment',
  '请描述 Web 应用需求，我将生成 React / Vue 站点与配套后端，可部署上线、对接真实服务...':
    'Describe the Web app and I will generate a React / Vue site with backend, deployable online with real services...',
  'AI生成App': 'AI Generate Mobile App',
  '移动端 / H5 / 跨端（React 或 Vue），含后端与发布交付':
    'Mobile / H5 / cross‑platform (React or Vue) with backend & publishable delivery',
  '请描述移动端或跨端应用需求，我将基于 React / Vue 技术栈生成可运行工程（含 H5 / 跨端），可搭配后端与发布能力交付...':
    'Describe the mobile or cross‑platform app and I will generate a runnable React / Vue project (H5 / cross‑platform) with backend & publishing...',
  '一句话生成可交互 HTML 原型，可走查/评审': 'One‑sentence interactive HTML prototype, ready to review',
  '请描述原型需求或上传 PRD，我将生成可交互 HTML 原型（不生成 React / Vue 全栈与后端工程）...':
    'Describe the prototype or upload the PRD and I will generate an interactive HTML prototype (not a React / Vue full‑stack or backend project)...',
  '上传截图 / 草图，一键转为 HTML 原型': 'Upload screenshot / sketch → interactive HTML prototype',
  '请上传截图或草图，我将识别界面结构并生成可交互 HTML 原型...':
    'Upload a screenshot or sketch and I will build an interactive HTML prototype...',
  '上传 HTML 文件，一键导入为墨刀原型': 'Upload HTML → import into Prodes prototype',
  '请上传 HTML 文件或粘贴代码，我将一键转换为墨刀可交互原型...':
    'Upload HTML file or paste code and I will convert it to an interactive Prodes prototype...',
  '生成 Web 应用': 'Generate Web App',
  '生成 App 应用': 'Generate Mobile App',
  'AI生成原型': 'AI Prototype',
  '一键生成可交互原型': 'Generate interactive prototype',
  '数据可视化运营大屏': 'Operations data dashboard',
  '数据大屏原型': 'Dashboard Prototype',
  '运营监控 / 指标看板 / 趋势大屏': 'Ops monitoring, KPI dashboards, and trend screens',
  '经营看板与趋势大屏': 'Business dashboards and trend screens',
  '监控/运营/能耗看板，多文件 HTML 可演示交付': 'Ops/energy dashboards, multi-file HTML demo',
  '企业后台管理系统': 'Enterprise admin system',
  '后台管理原型': 'Admin Prototype',
  'CRM / ERP / 权限后台页面': 'CRM, ERP, and role-based admin pages',
  '后台系统': 'Admin System',
  'CRM / 表格 / 权限后台': 'CRM, tables, and role-based admin',
  'CRM/权限/表格/工单，常见 B 端后台原型': 'CRM, roles, tables, tickets—typical B-end admin',
  '界面复刻设计': 'UI replication',
  '截图复刻原型': 'Screenshot Recreation Prototype',
  '参考图高保真还原与迁移': 'High-fidelity recreation and migration from references',
  '界面复刻': 'UI Recreation',
  '参考图高保真还原': 'High-fidelity recreation from references',
  '参考图/截图高保真还原与迁移': 'High-fidelity from screenshots or references',
  '小程序 / App原型': 'Mini Program / App Prototype',
  '电商 / 问诊 / 社交多页原型': 'Multi-page prototypes for commerce, telehealth, and social apps',
  '移动应用': 'Mobile App',
  'App / 小程序多页原型': 'App or mini-program multi-page prototype',
  '请描述行业与指标，例如：智慧医院运营大屏，含实时床位、手术量、能耗与告警分区；或节能减排数据看板，含 KPI 卡片与趋势图...':
    'Describe industry & metrics, e.g. hospital ops screen with beds, surgeries, energy, alerts; or carbon dashboard with KPI cards and trends...',
  '请描述后台类型与核心模块，例如：CRM 客户跟进、工单、权限角色、数据导入导出、列表筛选与详情抽屉...':
    'Describe admin type & modules, e.g. CRM follow-up, tickets, roles, import/export, filters and detail drawers...',
  '请说明参考来源与目标，例如：上传截图高保真复刻、对标某 App 风格迁移、或从 Figma 导出后的页面还原...':
    'Describe reference & goal, e.g. replicate a screenshot, match an app style, or restore from Figma export...',

  // 首页推荐 Top9
  '单页网页原型': 'Single-page Website Prototype',
  '单页网页': 'Single-page Website',
  '落地页 / 官网 / 说明页': 'Landing page, website, or docs page',
  '落地页 / 官网 / 说明页原型': 'Landing pages, websites, and documentation prototypes',
  '单页组件原型': 'Single-page Component Prototype',
  '轻应用页': 'Light App Page',
  '登录页 / 表单 / 小工具': 'Login page, form, or small utility',
  '登录页 / 表单 / 小工具原型': 'Login pages, forms, and tool prototypes',
  '请描述行业、指标与分区，例如：智慧医院运营大屏含床位/手术量/能耗与告警；或电商实时 GMV、渠道转化与库存预警看板，多文件 HTML 可演示...':
    'Describe industry, metrics & layout, e.g. hospital ops screen with beds/surgeries/energy/alerts, or e‑commerce GMV, funnel & stock alerts—multi-file HTML demo...',
  '请描述业务与核心页面流，例如：生鲜电商「首页-分类-商详-购物车-结算」；或在线问诊「挂号-候诊-视频问诊-处方」多页 C 端原型...':
    'Describe business & page flow, e.g. fresh grocery home→category→PDP→cart→checkout, or telehealth register→queue→video→prescription...',
  '请描述管理端类型与模块，例如：CRM 客户跟进与商机阶段、工单流转、角色权限、表格筛选与详情抽屉、数据导入导出...':
    'Describe admin type & modules, e.g. CRM pipeline & stages, ticket flow, RBAC, table filters & drawers, import/export...',
  '请说明参考来源与还原目标，例如：上传截图高保真复刻、对标某 App 迁移、或 Figma 导出后的页面还原为可点击 HTML...':
    'Describe source & goal, e.g. screenshot replication, clone a reference app, or turn Figma export into clickable HTML...',
  '可视化大屏案例': 'Visual Dashboard Case',
  'App/小程序案例': 'App / Mini Program Case',
  'B端管理后台案例': 'B-end Admin Console Case',
  '参考图复刻原型案例': 'Reference-based Prototype Recreation Case',
  '图片转原型案例': 'Image to Prototype Case',
  '需求文档PRD案例': 'PRD Document Case',
  'AI生成PPT案例': 'AI PPT Case',
  'AI美化PPT案例': 'AI PPT Beautifier Case',
  '美化PPT案例': 'Polished deck case',
  '图片转视频案例': 'Image to Video Case',
  '请描述零散页面或说明类需求，例如：官网介绍页、活动落地页、导入说明、评审用多页 HTML 或配套 Markdown 说明...':
    'Describe one-off pages or docs, e.g. marketing site, campaign LP, import notes, review pack HTML + Markdown...',
  '请描述产品背景与功能范围，我将输出可评审的结构化 PRD：用户故事、流程、边界与验收要点（常配说明型 HTML）...':
    'Describe context & scope; I will output a review-ready PRD: stories, flows, boundaries & acceptance (often with explanatory HTML)...',
  '请描述单页或小模块，例如：登录/注册页、计算器、配置面板、轻量 H5 活动页，少量 HTML 快速可点...':
    'Describe a single page or widget, e.g. login/signup, calculator, settings panel, light campaign H5—minimal clickable HTML...',

  // Tooltips / actions
  '切换演示设备': 'Switch device',
  '切换页面': 'Switch page',
  '刷新': 'Refresh',
  '新窗口打开': 'Open in new tab',
  '全屏': 'Full screen',
  '关闭': 'Close',
  '下载代码': 'Download code',
  '复制代码': 'Copy code',
  '代码复制成功': 'Code copied',
  '复制失败，请重试': 'Copy failed. Try again',

  // 墨刀工作台首页（与本地 WorkbenchHomePage 一致）
  '搜索文件、素材': 'Search files and assets',
  墨刀原型: 'Modao Prototype',
  墨刀白板: 'Modao Whiteboard',
  墨刀AIPPT: 'Modao AIPPT',
  '原型 交互 线框': 'Wireframes · Interactions',
  '需求 项目 协作': 'Requirements · Collab',
  '方案 总结 宣传': 'Decks · Summary · Pitch',
  'AI聚力 想法即刻成型': 'AI brings ideas to life, instantly',
  '上传截图或输入需求，一键生成完整交互原型': 'Upload a screenshot or describe—build a full interactive prototype in one go',
  '墨刀AI 原型': 'Modao AI · Prototype',
  '请描述您想要的界面，或上传附件作为参考': 'Describe the screen you want, or attach a reference',
  'AI发散 创意无限': 'Diverge with AI, explore without limits',
  '用思维导图与流程图，把想法变成可协作的产出': 'Mind maps and flowcharts that turn ideas into team-ready output',
  '导入大纲或长文档，一键生成精美 PPT 排版与配图':
    'Import an outline or long document—one click to layout and slides with visuals',
  '墨刀AI 白板': 'Modao AI · Whiteboard',
  '输入你想分析或拆解的任务': 'Enter the task you want to break down or analyze',
  'AI凝练 汇报瞬间出彩': 'Condense with AI, make every deck stand out',
  '导入大纲或长文档，一键排版生成精美演示文稿': 'Import an outline or long doc—one click to a polished deck',
  '墨刀AI AIPPT': 'Modao AI · AIPPT',
  快速开始: 'Quick start',
  精选模版: 'Featured templates',
  向左滚动: 'Scroll left',
  向右滚动: 'Scroll right',
  最近文件: 'Recent files',
  大厂资源: 'Big tech assets',
  管理后台: 'Management backend',
  官网: 'Web',
  绘图与创作: 'Drawing & creation',
  '调研分析': 'Research',
  '灵感/笔记': 'Inspiration & notes',
  项目管理: 'Project mgmt',
  头脑风暴: 'Brainstorm',
  策略分析: 'Strategy',
  '会议/工作坊': 'Workshops',
  'IT互联网': 'IT & internet',
  教学课件: 'Courseware',
  商业计划书: 'Business plan',
  学术答辩: 'Thesis defense',
  研究报告: 'Research report',
  '暂无最近文件，去创建一个吧': 'No recent files yet—create one to get started',
  新建空白原型: 'New blank prototype',
  '+ 新建空白原型': '+ New blank prototype',
  'HTML转墨刀原型': 'HTML to Modao prototype',
  导入Axure: 'Import Axure',
  常用图表: 'Common charts',
  'APP通用页面': 'App screens',
  小程序原型: 'Mini program',
  企业官网: 'Corporate site',
  新建空白白板: 'New blank whiteboard',
  '+ 新建空白白板': '+ New blank whiteboard',
  创建思维导图: 'New mind map',
  新建流程图: 'New flowchart',
  'APP页面模板': 'App page templates',
  敏捷看板: 'Agile board',
  团队头脑风暴: 'Team brainstorm',
  产品需求文档: 'PRD',
  泳道流程图: 'Swimlane flow',
  新建空白PPT: 'New blank deck',
  '+ 新建空白PPT': '+ New blank deck',
  导入生成PPT: 'Import to generate PPT',
  链接生成PPT: 'From link to PPT',
  产品经理年终总结: 'PM year-end review',
  总结汇报: 'Status report',
  'AI智能研究报告': 'AI research report',
  前景分析报告: 'Trend outlook',
  输入演讲主题: 'Your presentation topic',

  // 父级墨刀工作台（侧栏与主区，与墨刀AI 子站分离）
  墨刀: 'Modao',
  我的收藏: 'Favorites',
  素材广场: 'Asset plaza',
  我的文件: 'My files',
  回收站: 'Trash',
  空间管理: 'Space admin',
  素材库: 'Asset library',
  文件数: 'File usage',
  升级会员: 'Upgrade',
  功能建设中: 'Under construction',
  '演示环境仅展示父级「墨刀工作台」导航结构': 'Demo: parent workbench navigation only',
  '更多企业能力与开放合作能力敬请期待，可在子产品中开始创作。':
    'More enterprise features are coming—start creating in a product workspace.',
  'AI发散 激发无限灵感': 'AI sparks infinite ideas',
  '✨ 输入核心主题，秒速生成思维导图与业务流程':
    'Enter a theme—mind maps and business flows in seconds',
  墨刀设计: 'Modao Design',
  '界面 视觉 UI': 'UI · Visual',
  '墨刀AI 设计': 'Modao AI · Design',
  'AI灵感 设计所见即所得': 'AI ideation—design that matches what you describe',
  '描述风格、组件与页面结构，快速生成可编辑高保真设计稿':
    'Describe styles, components, and pages—editable hi-fi design, fast',
  '更多企业能力 · 开放合作': 'More · Open platform',
  '请输入内容…': 'Type here…',
  新建思维导图: 'New mind map',
  'APP原型模板': 'App prototype template',
  团队脑暴: 'Team brainstorm',
  甘特图: 'Gantt',
  绘图: 'Draw',
  '策略&分析': 'Strategy & analysis',
  '会议&工作坊': 'Meetings & workshops',
  企业管理: 'Enterprise',
  营销: 'Marketing',
  企业宣传: 'Corporate comms',
  'AI 凝练 汇报瞬间出彩': 'AI distills, decks stand out',
  界面合集: 'UI sets',
  UI组件集: 'UI kits',
  图标: 'Icons',
  移动设计: 'Mobile design',
  网页设计: 'Web design',
  线框图: 'Wireframes',
  导入设计稿: 'Import design file',
  微信小程序组件库: 'WeChat component library',
  'Element UI 组件库': 'Element UI',
  'Ant Design 组件库': 'Ant Design',
  'AI 聊天APP套件': 'AI chat app kit',
  'HarmonyOS 组件库': 'HarmonyOS library',
  新建空白设计: 'New design file',
  '+ 新建空白设计': '+ New design file',
  'WeUI 微信组件': 'WeUI for WeChat',
  'Arco Design 字节': 'Arco (ByteDance)',
  'WeUI Dark': 'WeUI dark',
  'HarmonyOS 穿戴': 'HarmonyOS wearables',
  'HarmonyOS 多终端': 'HarmonyOS multi-device',
  'AI对话页面': 'AI chat page',
  'HMI通用模板': 'HMI template',
  '绘图&创作': 'Draw & create',
  HMI: 'HMI',
  '企业能力 · 开放合作': 'Enterprise · Open',
  产研一站智能体: 'One-stop AI agent for product & R&D',
  '对话 生成 一站创作': 'Chat, generate, create in one place',
  '步骤有序，流向一目了然': 'Clear steps, flow at a glance',
  '逻辑梳理，创意跃然纸上': 'Structure ideas, creativity on the page',
  '团队协同，管理各项交付': 'Team sync, track every deliverable',
  '快速导入，轻松再编辑': 'Import fast, edit with ease',
  '在线分享，二次编辑': 'Share online, refine anytime',
  导入墨刀原型源文件: 'Import Modao prototype file',
  '导入墨刀.mdrp源文件': 'Import a Modao .mdrp file',
  新建旧版文件: 'New legacy file',
  '原型 流程图': 'Prototype · flowchart',

  // Workbench · 原型 Tab 快捷项填入输入框
  '请生成一个B端管理后台中保真原型，包含左侧可折叠导航、顶栏、用户/角色与权限相关列表和详情/表单，注意空态与面包屑。':
    'Create a mid-fidelity B-end admin console: collapsible sidebar, top bar, user/role and permission lists with detail/forms, empty states and breadcrumbs.',
  '请生成一套移动端APP通用页面线框：底部Tab（首页/列表/我的等）、典型列表与详情、常见弹窗，竖屏约375宽。':
    'Wireframe a typical mobile app set: bottom tabs (home/list/profile), list & detail, common dialogs, ~375px wide portrait.',
  '请生成微信小程序中保真原型，含首页、搜索/列表、个人中心，符合微信规范与 750 设计宽度假设。':
    'Mid-fidelity WeChat mini program: home, search/list, profile, following WeChat patterns and 750rpx width assumptions.',
  '请生成企业官网多页线框：首页主视觉与CTA、产品/方案、关于与联系，偏简洁商务风。':
    'Multi-page corporate site wireframes: home hero & CTA, product/solutions, about & contact—clean business style.',
  '请生成AI对话应用界面线框，含会话列表、聊天主界面、输入区与历史/设置入口。':
    'AI chat app wireframes: conversation list, main chat, input area, history/settings entry.',
  '请生成数据可视化运营大屏中保真稿，深色主题，含顶部KPI、趋势区、明细表或地图占位。':
    'Ops data dashboard mid-fidelity, dark theme: top KPIs, trend area, detail table or map placeholder.',
  '请生成车载或工控HMI通用页面线框，含车速/状态区、功能入口与告警条，大字号、高对比。':
    'Vehicle or industrial HMI wireframes: speed/status, feature entries, alert bar—large type, high contrast.',

  // Workbench · 白板 Tab 快捷（APP 原型模板之后）
  '请根据我的主题生成敏捷看板白板：含待办/进行中/完成等列，可带泳道或标签，并预留迭代与站会记录区。':
    'From my topic, build an agile kanban whiteboard: to-do/doing/done columns, optional swimlanes or tags, space for sprints and standup notes.',
  '请围绕中心议题组织团队脑暴白板：中心主题、多轮分支联想、便签区与简单优先级/投票区。':
    'Run a team brainstorm: central topic, branching ideation, sticky area, and simple priority/voting zone.',
  '请生成产品需求文档（PRD）大纲式白板：项目背景、目标用户、用户故事/功能表、非功能、验收与发布节奏，用层级或思维导图结构呈现。':
    'Create a PRD-style outline whiteboard: background, users, stories/features, NFRs, acceptance and release—hierarchy or mind map shape.',
  '请生成泳道流程图：按角色或系统区分泳道，标出主流程步骤、判断节点与系统边界。':
    'Build a swimlane flow by role or system: main steps, decision points, and handoffs.',
  '请根据项目任务生成甘特式时间线白板：任务名称、起止时间、依赖关系与里程碑，可用横向时间轴排布。':
    'Gantt-style timeline: tasks, start/end, dependencies, and milestones on a horizontal axis.',

  // Workbench · 设计 Tab 快捷（第三个起：微信组件库 …）
  '请基于 WeUI/微信设计规范输出小程序高保真设计：含首页、列表/搜索、表单与个人中心，说明组件选用与 750 宽栅格习惯。':
    'Hi-fi WeChat mini program UI per WeUI: home, list/search, forms, profile—note components and 750rpx grid habits.',
  '请基于 Element Plus 输出中后台高保真界面：顶栏+侧栏布局、典型表格/筛选、表单与弹窗，企业蓝白风格，附关键页面结构说明。':
    'Hi-fi Element Plus admin: header+sidebar, tables/filters, forms, dialogs—enterprise blue/white, key page notes.',
  '请基于 Ant Design 输出中后台高保真界面：ProLayout、表格/表单/抽屉等组合，数据展示与操作反馈完整，可注明 Design Token 倾向。':
    'Hi-fi Ant Design admin: ProLayout, table/form/drawer patterns, full data & feedback—optional token hints.',
  '请输出 AI 聊天类 App 高保真设计：对话列表、单聊/多模态输入区、历史与设置，偏现代轻量，含空态与加载态。':
    'Hi-fi AI chat app: thread list, chat with multimodal input, history/settings—light modern style, empty & loading.',
  '请基于 HarmonyOS 设计规范输出端侧高保真稿：信息架构、列表/卡片、设备能力入口，注意字体层级与系统色使用。':
    'Hi-fi HarmonyOS UI: IA, lists/cards, device capability entries—typography hierarchy and system colors.',

  // Workbench · 墨刀AIPPT 快捷（产品经理年终总结起）
  '请生成「产品经理年终总结」PPT 的章节与逐页要点：年度目标、关键项目与数据成果、问题复盘、协作与成长、明年规划；注明每页建议图表或配图。':
    'PM year-end review deck: goals, key projects & metrics, retros, collaboration & growth, next year—per-slide bullets and chart/art notes.',
  '请生成通用「总结汇报」类 PPT 结构：背景与目标、阶段进展、核心数据、风险与问题、下阶段计划与资源需求，适合对内对外汇报。':
    'Generic summary report deck: context & goals, progress, KPIs, risks, next plan & resources—works for internal or external.',
  '请按「AI 智能研究报告」体例输出 PPT 大纲：摘要、研究背景、方法/实验、数据与对比、结论与局限、未来工作；附图表/公式占位建议。':
    'AI research report style: abstract, background, method/experiments, data & comparison, conclusions & limits, future work—figure/formula placeholders.',
  '请输出「前景分析」类 PPT：行业与市场现状、驱动因素、趋势与机会、主要风险、竞争格局、结论与策略建议，咨询报告版式。':
    'Prospect analysis deck: market today, drivers, trends & opportunities, risks, competition, conclusions & strategy—consulting layout.',
};
