export const PC_EN_DICT: Record<string, string> = {
  // Product name
  '墨刀AI': 'Prodes AI',
  '墨刀 AI': 'Prodes AI',
  '墨刀AI设计助手': 'Prodes AI design assistant',
  '展开左侧栏': 'Expand sidebar',
  '新建项目': 'New project',
  '购买': 'Buy',
  '生成一个电商购物App首页': 'Generate an e-commerce shopping app home screen',
  '你好！我是墨刀 AI 设计助手，专注于完整的端到端产品架构生成与开发。': "Hi! I'm Prodes AI design assistant, focused on end-to-end product design and build.",
  '你可以对我说："生成一个带深色模式的现代任务管理 SaaS 后台" 或 "帮我做一个电商小程序的商品列表页"。': 'Try: "Build a modern task SaaS admin with dark mode" or "Design a product list page for an e-commerce mini app".',
  '分享项目': 'Share project',
  '分享文件': 'Share file',
  '把整个对话和对话中生成的所有内容分享出去': 'Share the whole conversation and everything generated in it',
  '只分享当前所选的文件': 'Only share the selected file',
  '展开助手': 'Expand assistant',
  '墨刀AI的虚拟电脑': 'Prodes AI virtual computer',
  '已完成编辑': 'Edited',
  '设计评审': 'Design review',
  '设计评审文档': 'Design review doc',
  '分享': 'Share',
  '复制': 'Copy',
  '下载': 'Download',
  '历史版本': 'History',
  '设置类别': 'Settings',
  '目录': 'Files',
  '收起目录': 'Collapse files',
  '请框选要调整的区域并告诉AI如何修改': 'Select an area and tell the AI what to change',
  '添加到对话': 'Add to chat',
  '暂无可预览的内容': 'Nothing to preview',
  '确定要撤回该项目的发布吗？': 'Withdraw this publish?',
  '撤回后线上链接将立即失效。': 'The live link will be disabled immediately.',
  '撤回成功': 'Withdrawn',
  '确定': 'Confirm',
  '截图优化': 'Screenshot mode',
  'PC 端': 'PC',
  'Pad 端': 'Pad',
  '已保存至云端': 'Saved to cloud',
  '撤销上一步': 'Undo',
  '重做': 'Redo',
  '下载当前文件': 'Download current file',
  '下载所有文件': 'Download all files',
  '链接访问权限': 'Link access',
  '仅限自己': 'Only me',
  '仅自己可见': 'Visible only to you',
  '公开': 'Public',
  '获得链接的人可访问': 'Anyone with the link can access',
  '回放模式': 'Replay mode',
  '复制链接': 'Copy link',
  '发布网站': 'Publish site',
  '项目名称': 'Project name',
  '当前状态': 'Status',
  '已发布': 'Published',
  '未发布': 'Not published',
  '最近发布时间': 'Last published',
  '访问链接': 'Access link',
  '点击在新标签页打开': 'Open in new tab',
  '点击在新标签页打开预览': 'Open preview in new tab',
  '保存': 'Save',
  '取消': 'Cancel',
  '编辑域名前缀': 'Edit subdomain',
  '撤回': 'Withdraw',
  '正在撤回...': 'Withdrawing...',
  '✅ 更新成功！': 'Update successful',
  '更新': 'Update',
  '正在更新...': 'Updating...',
  '更新成功': 'Updated',
  '✅ 发布成功！网站已上线': 'Published. Your site is live.',
  '发布': 'Publish',
  '正在发布...': 'Publishing...',
  '刚刚': 'Just now',
  '{{n}} 分钟前': '{{n}} min ago',
  '{{n}} 小时前': '{{n}} hr ago',
  '{{n}} 天前': '{{n}} d ago',
  '等待生成内容': 'Waiting for output',
  '在左侧输入需求，AI将为您生成产品并在右侧展示': 'Describe your needs on the left. The AI will generate and show results on the right.',
  'AI 正在生成中，请稍候...': 'Generating. Please wait...',
  'AI 正在绘制界面结构并添加样式...': 'Building layout and styles...',
  '代码正在流式渲染...': 'Streaming code...',
  '接收流式代码中...': 'Receiving stream...',
  '等待代码生成...': 'Waiting for code...',
  '暂不支持当前模式': 'Not supported yet',
  '此 Tab 规划中，将在后续版本上线': 'Planned for a future release',
  '分析需求结构...': 'Analyzing requirements...',
  '搭建页面框架': 'Building page structure',
  '已完成创建 {{file}}': 'Created {{file}}',
  '正在整合样式资源...': 'Integrating styles...',
  '正在执行...': 'Running...',
  '正在生成代码（{{n}} 字符）...': 'Generating code ({{n}} chars)...',
  '已为您生成以下内容，点击卡片可在右侧查看：': 'Generated the following. Click a card to view on the right:',
  '文档': 'Doc',
  '单页': 'Single page',
  '多页': 'Multi-page',
  '应用': 'App',
  'App原型': ' app prototype',
  '该链接已被占用': 'This link is taken',
  '正在理解需求...': 'Understanding requirements...',
  '分析产品架构...': 'Analyzing product structure...',
  '准备生成方案...': 'Preparing a solution...',
  '请根据提供的截图优化': 'Optimize based on the provided screenshot',
  '电商购物App原型': 'E-commerce shopping app prototype',
  '墨刀 AI 设计助手': 'Prodes AI design assistant',
  '导出至墨刀': 'Export to Prodes',
  'HTML 转墨刀原型': 'HTML to Prodes prototype',
  '产品团队': 'Product team',
  '超级智能体': 'AI assistant',
  '下午好，我能如何帮助您': 'Good afternoon. How can I help',

  // Common UI
  '首页': 'Home',
  '知识库': 'Library',
  '历史对话': 'History',
  '新建对话': 'New chat',
  '收起左侧栏': 'Collapse sidebar',
  '下载移动端': 'Get mobile app',
  '扫码下载移动端，把专业墨刀AI能力装进口袋': 'Scan to get the mobile app',
  '联系客服': 'Contact support',
  '精选案例': 'Featured',
  '网页端': 'Web',
  '移动端': 'Mobile',
  'SaaS业务控制台': 'SaaS dashboard',
  'SaaS落地页设计': 'SaaS landing page',
  '文旅一站式平台': 'Travel platform',
  '古风数字景区App设计': 'Scenic app',
  '生鲜商城购物车': 'Grocery cart',
  '生鲜/电商APP原型': 'E-commerce app',
  '在线视频教学平台': 'Online learning',
  '在线教育界面设计': 'Education UI',
  '新建': 'Create',
  '请输入任何产品领域的需求或问题...': 'Describe what you want to build...',
  '极速': 'Fast',
  '深度': 'Deep',
  '快速生成': 'Quick draft',
  '深度思考': 'Deeper reasoning',
  '主题色': 'Theme',
  '外观': 'Appearance',
  '亮色': 'Light',
  '暗色': 'Dark',
  '自动': 'Auto',
  '蓝': 'Blue',
  '绿': 'Green',
  '紫': 'Purple',
  '橙': 'Orange',
  '黄': 'Yellow',
  '红': 'Red',
  '极速模式': 'Fast',
  '深度模式': 'Deep',
  '响应速度更快，适合简单问答': 'Faster, best for simple tasks',
  '内容质量更高，适合复杂任务': 'Better quality for complex tasks',
  '工作台': 'Workspace',

  // Tabs
  '预览': 'Preview',
  '编辑': 'Edit',
  '代码': 'Code',
  '配置': 'Settings',
  '分析': 'Analytics',

  // Tooltips / actions
  '切换演示设备': 'Switch device',
  '切换页面': 'Switch page',
  '刷新': 'Refresh',
  '新窗口打开': 'Open in new tab',
  '全屏': 'Full screen',
  '关闭': 'Close',
  '下载代码': 'Download code',
  '复制代码': 'Copy code',
  '代码复制成功': 'Code copied',
  '复制失败，请重试': 'Copy failed. Try again',
};

